version: '2'
services:
    javareactpres-app:
        image: javareactpres
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://javareactpres-mysql:3306/javareactpres?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8999:8999
    javareactpres-mysql:
        extends:
            file: mysql.yml
            service: javareactpres-mysql
